language: node_js
node_js:
    - 12
dist: xenial
addons:
    chrome: stable
before_install:
    - npm install -g @angular/cli
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install: npm install
deploy:
    provider: heroku:git
    api_key:
        secure: $HEROKU_API_KEY
    edge: true
    app: shannen-daily-planner
    on:
        branch: main
    strategy: git
