language: node_js
node_js:
    - 12
before_install:
    - npm install -g @angular/cli
install: npm install
deploy:
    provider: heroku
    api_key:
        secure: $HEROKU_API_KEY
    edge: true
    app: shannen-daily-planner
    on:
        branch: main
    strategy: git
