language: node_js
node_js:
    - node
deploy:
    provider: heroku:git
    api_key:
        secure: $HEROKU_API_KEY
    edge: true
    app: shannen-daily-planner
    on:
        branch: main
    strategy: git
